name: cornorshop
description: Graduation Project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: #for translation
    sdk: flutter
  intl_phone_field:
    path: 'intl_phone_field'


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  cached_network_image: ^3.2.3
  image_picker: ^0.8.9
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  dropdown_search: ^5.0.6
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/



  fonts:
      - family: NotoKufiArabic
        fonts:
          - asset: assets/fonts/NotoKufi/NotoKufiArabic-Bold.ttf
          - asset: assets/fonts/NotoKufi/NotoKufiArabic-Regular.ttf
          - asset: assets/fonts/NotoKufi/NotoKufiArabic-SemiBold.ttf
          - asset: assets/fonts/NotoKufi/NotoKufiArabic-Medium.ttf

    #         style: Bold
      - family: TitilliumWeb
        fonts:
          - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Bold.ttf
          - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Regular.ttf
          - asset: assets/fonts/TitilliumWeb/TitilliumWeb-SemiBold.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
